// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/service.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"
	model "testingmatcher-with-option/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// MakeARequest mocks base method.
func (m *MockService) MakeARequest(arg0 model.MyRequest) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeARequest", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MakeARequest indicates an expected call of MakeARequest.
func (mr *MockServiceMockRecorder) MakeARequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeARequest", reflect.TypeOf((*MockService)(nil).MakeARequest), arg0)
}
